
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

//package contractfirst;
package com.namespacetest.shopping;

import java.math.BigDecimal;
import java.util.logging.Logger;

import com.namespacetest.orderTypes.ConfirmationType;
import com.namespacetest.orderTypes.ConfirmationType.Item;
import com.namespacetest.purchase.ConfirmationDocument;
import com.namespacetest.shopping.PurchasePortType;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-12T22:17:29.943-04:00
 * Generated source version: 2.7.10
 * 
 */

//locations specified here are superseeded by the declarations done in endpoint. 


@javax.jws.WebService(
                      serviceName = "PurchaseService",
                      portName = "PurchasePort",
                      targetNamespace = "http://Namespacetest.com/shopping",
                      wsdlLocation = "classpath:shopping.wsdl",
                      endpointInterface = "com.namespacetest.shopping.PurchasePortType")
                      
public class PurchasePortTypeImpl implements PurchasePortType {

    private static final Logger LOG = Logger.getLogger(PurchasePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.namespacetest.shopping.PurchasePortType#purchase(com.namespacetest.purchase.PurchaseDocument  purchase ,)com.namespacetest.purchase.CustomerDetailsDocument  customer )*
     */
    public com.namespacetest.purchase.ConfirmationDocument purchase(com.namespacetest.purchase.PurchaseDocument purchase,com.namespacetest.purchase.CustomerDetailsDocument customer) { 
        LOG.info("Executing operation purchase");
        System.out.println(purchase);
        System.out.println(customer);
        try {
            com.namespacetest.purchase.ConfirmationDocument _return = ConfirmationDocument.Factory.newInstance();
            ConfirmationType confirmation = _return.addNewConfirmation();
            Item item = confirmation.addNewItem();
            item.setStatus("Executed");
            item.setProductName("Ordered Product");
            item.setUnitPrice(new BigDecimal(2.30));
            
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
