
package contractfirst;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.math.BigDecimal;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.namespacetest.customerTypes.CustomerType;
import com.namespacetest.orderTypes.OrderType;
import com.namespacetest.purchase.CustomerDetailsDocument;
import com.namespacetest.purchase.PurchaseDocument;
import com.namespacetest.purchase.PurchaseDocument.Purchase;
import com.namespacetest.shopping.PurchasePortType;
import com.namespacetest.shopping.PurchaseService;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-13T00:44:01.506-04:00
 * Generated source version: 2.7.10
 * 
 */
public final class PurchasePortType_PurchasePort_Client {

    private static final QName SERVICE_NAME = new QName("http://Namespacetest.com/shopping", "PurchaseService");

    private PurchasePortType_PurchasePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PurchaseService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PurchaseService ss = new PurchaseService(wsdlURL, SERVICE_NAME);
        PurchasePortType port = ss.getPurchasePort();  
        
        System.out.println("Invoking purchase...");
        com.namespacetest.purchase.PurchaseDocument _purchase_purchase = PurchaseDocument.Factory.newInstance();
        Purchase purchase = _purchase_purchase.addNewPurchase();
        OrderType order = purchase.addNewOrderDetail();
        OrderType.Item item = order.addNewItem();
        item.setProductName("Hello Product");
        item.setQuantity(10);
        item.setUnitPrice(new BigDecimal(5.0));
        com.namespacetest.purchase.CustomerDetailsDocument _purchase_customer = CustomerDetailsDocument.Factory.newInstance();
        CustomerType customer = _purchase_customer.addNewCustomerDetails();
        customer.setName("Vamsi");
        
        com.namespacetest.purchase.ConfirmationDocument _purchase__return = port.purchase(_purchase_purchase, _purchase_customer);
        System.out.println("purchase.result=" + _purchase__return);


        System.exit(0);
    }

}
